travis:
  secure:
    BINSTAR_TOKEN: XrSExUKuaJW4UjTRh1yp+Lj74jaED52si4Ec7EjEVlSZLcbq7ZPQA0xD6J6vHgy6IqKx1G/f/T4MXnCplB+r625NONhglAhpJwyqIssnsBd7O9Zdn0o9GWeZPjtSlpj3TNnnQQ+Wk9pX73o07Wv2bMcC/mltlI5SR+dFlAimE1c5MguqKBkU9MGE52ahbM+qDoNs6JL29KY4SSawOfVLcuQVdVdVCXKrmytzB0XpWGFhxJxGkzpkgJ0Ifw43Am2IiHKfPvAFydIeAL7Fi7JIjabZhCCLRuJO09H4h2VeCytvezpeI26/JDS7TTIVLGvjTNoWuc3G/pV5NV7iITp3Co2YNTmYMrh7YQz+GDXStkibgj5WFQlf6iiY7eKNVUKhfdiMdmNpCXMQTORVNVdKakAVpzi4yIfaU314OAbrt4WzsDxFO0oGaegjniWEqVroexmcP474CXqBluZcDrfqr6GGhQ+ycNZZpY36C928tGNjvmti9S1KC7ep8Cwbar1mh3zcAMwM2IsArMEYC6iu6RCRmPQgBqpZEadcuRZJo4Lm1+ktFzn/ZuUlLXk220XJMwXP5nfpT6De65uKkUAmTypdmO8WphaG2czIgilDB3vB1vpmOSQJjo0Su+Wl/TI4mv77Q7AX/s7BwK6JhTVyWjGjcXBwhD7Xls7/XL8pwR8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
